name: tutorial
dependencies:
  - python=3.6
  - pip:
    - --index-url https://pypi.tuna.tsinghua.edu.cn/simple
    - numpy==1.16.2
    - pyspark==2.4.3
    - pandas==0.24.2
    - scikit-learn==0.20.3
    - scipy==1.2.1
    - kafka==1.3.5